version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  db-server:
    image: pradipsolunke/server:db-server
    container_name: db-server
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017
    ports:
      - 8080:8080
    links:
      - mongodb