apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-server
  name: db-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-server
  template:
    metadata:
      labels:
        app: db-server
    spec:
      containers:
        - image: pradipsolunke/server:db-server
          imagePullPolicy: Always
          name: db-server
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
          resources:
            requests:
              memory: 700Mi
              cpu: 100m
            limits:
              memory: 700Mi
              cpu: 1
          ports:
            - containerPort: 8080
              protocol: TCP